### ISSUE TITLE
Fresh roll-out apt_key dependency error

### ISSUE THREAD

**Issue by famfop** [Icinga/puppet-icinga#10]
I am trying to roll-out my environment on a fresh vm running Debian 10 (thus gnupg not being installed) but get the error notification that it failed to find `/usr/bin/gpg` (well, it does not exist...). This left me wondering, if there is an issue with this repository. I am currently simply using `include ::icinga::repos`. Can you reproduce this on a system without gnupg being pre-installed?

**Comment by lbetz** [comment]
In my opinion gpg is used for gpgcheck also for repos without puppet management.

**Comment by famfop** [comment]
Unfortunately my environment is pretty grown at this point and it is not easy for me to debug where the issue arises. It might be in this module, it might be inside apt. If you have a simple way to test this module on a vanilla debian 10 and it does not fail to install gnupg the issue should be in the apt-module - or I have a bug in the order of manifests being called. It'd be great if you could give me some feedback on this.

**Comment by lbetz** [comment]
The binary /usr/bin/gpg belongs to the package gpg that has to be installed. I never have seen a debian installation without the package gpg because a gpgcheck of package you install from repositories is common.
The icinga module doesn't manage the package gpg.

**Comment by famfop** [comment]
That's where I get confused. Indeed, gpg or the gnupg-package are not installed by default on Debian 10 and as far as I can see the puppet-apt-package should handle this, at least their "key.pp" and "init.pp" declare an `ensure_package['gnupg']`. For the former this should be triggered when calling `apt::source` in this repos `./manifests/repos/apt.pp` but I have trouble understanding line 23 of this manifest, or better: I cannot find where you set the `$manage_stable` (in repos.pp) to true, which in turn is necessary for the ensure to be set to present. But I guess somewhere in this chain the ensure should get lost thus preventing apt::key to trigger the necessary install of gnupg.

**Comment by lbetz** [comment]
It's done in hiera (data/Linux-kernel.yaml) on all Linux based systems.
