### ISSUE TITLE
manage_epel do not work

### ISSUE THREAD

**Issue by misaflo** [Icinga/puppet-icinga#20]
Hello,

When upgrading from version 2.0.0 to 2.1.2, `manage_epel` stop working.

It seems to be since [this commit](https://github.com/Icinga/puppet-icinga/commit/08e8cbd27463a9a929539e8084d4bb0674619271#diff-ea9414c4481ad97900f2b462b44229a4ffdced27fd7e2a58feffd8221a26dd25).

I have this :

    Notice: manage_epel: false
    Notice: enabled: {icinga-stable-release => true, icinga-testing-builds => false, icinga-snapshot-builds => false, epel => false, netways-plugins-release => false, netways-extras-release => false}

bug got this error:

    Duplicate declaration: Yumrepo[epel] is already declared at (file: /etc/puppetlabs/code/environments/toto/modules/epel/manifests/init.pp, line: 190); cannot redeclare (file: /etc/puppetlabs/code/environments/toto/modules/icinga/manifests/repos/yum.pp, line: 22)

Thanks for Icinga and this Puppet module.

**Comment by lbetz** [comment]
Shit, a merge failed.
