### ISSUE TITLE
Broken dependency for yumrepos

### ISSUE THREAD

**Issue by misaflo** [Icinga/puppet-icinga#22]
Hello,

A new bug with version 2.1.3 on CentOS:

    Could not find resource 'Yumrepo[icinga-testing-builds]' for relationship on 'Package[createrepo]'

I fix this with this modification on `manifests/repos/yum.pp`:

    $repos.each |String $repo_name, Hash $repo_config| {
      if $repo_name in keys($managed) and $managed[$repo_name] {
        yumrepo { $repo_name:
          *       =>  $repo_config,
          require => File['/etc/yum.repos.d/netways-plugins-release.repo', '/etc/yum.repos.d/netways-extras-release.repo'],
        }
      }
      Yumrepo[$repo_name] -> Package <| |>
    }

to:

    $repos.each |String $repo_name, Hash $repo_config| {
      if $repo_name in keys($managed) and $managed[$repo_name] {
        yumrepo { $repo_name:
          *       =>  $repo_config,
          require => File['/etc/yum.repos.d/netways-plugins-release.repo', '/etc/yum.repos.d/netways-extras-release.repo'],
        } -> Package <| |>
      }
    }

**Comment by lbetz** [comment]
Strange, don't see that makes a difference.

**Comment by lbetz** [comment]
before I publish a new release, can you test the master branch?

**Comment by misaflo** [comment]
Yes, it works (tested  on CentOS and Debian). :-)

**Comment by lbetz** [comment]
Thx, release is upcoming.
