### ISSUE TITLE
Change Management Behavoir for Repositories

### ISSUE THREAD

**Issue by fionera** [Icinga/puppet-icinga#6]
Currently when I include the class by enabling manage_repo, the `epel` Repo gets defined even when `manage_epel` is set to false. This collides with the following: https://forge.puppet.com/modules/puppet/epel

**Comment by lbetz** [comment]
Currently params like manage_epel always manage the repository resource and manage_* enable or disable the repo. Rework to manage the resources and NOT to enable/disable repos.

**Comment by lbetz** [comment]
@fionera if you like you can test branch fix/manage-repos-6

**Comment by fionera** [comment]
I currently have it set to my fork but since you took the same approach it should be fine :) Thank you

**Comment by lbetz** [comment]
Ok, of course I did more. Especially the same for the other supported plattforms.

I will perform acceptence tests and build a release tomorrow or maybe later today.

**Comment by fionera** [comment]
Thank you very much
