### ISSUE TITLE
error: Could not find template 'icinga/apache_custom_default.conf'

### ISSUE THREAD

**Issue by alexbugl** [Icinga/puppet-icinga#70]
When updating to `v2.9.0` I get the following error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error:
Error while evaluating a Function Call, Could not find template 'icinga/apache_custom_default.conf'
(file: /etc/puppetlabs/code/environments/dev/modules/icinga/manifests/web.pp, line: 213, column: 22)
```

Looks like you removed the template file `icinga/apache_custom_default.conf`, but did not change the corresponding code in `manifests/web.pp` ...

As I do not know why you removed the template, I currently can't suggest a solution.

Best regards, Alex

**Comment by lbetz** [comment]
What the f..., the whole directory is gone.
