### ISSUE TITLE
Duplicate declaration: Yumrepo[epel] is already declared

### ISSUE THREAD

**Issue by triforce** [Icinga/puppet-icinga#9]
When using this and the https://github.com/voxpupuli/puppet-yum module I am getting a duplicate resource error:

Duplicate declaration: Yumrepo[epel] is already declared at:

modules/yum/manifests/init.pp, line: 136
modules/icinga/manifests/repos/yum.pp, line: 20

Should this module be checking for the existence of the Yumrepo[epel] before declaring the resource or is this a configuration problem on my behalf?

I am using version 2.0.0 of both modules.

**Comment by lbetz** [comment]
Yes, please disable the epel repository in one of both modules. For icinga::repos set attribute manage_epel => false or set icinga::repos::manage_epel: false in your hier configuration.

**Comment by triforce** [comment]
Thank you that works
