### ISSUE TITLE
Support for puppetlabs-stdlib < 10.0.0

### ISSUE THREAD

**Issue by bk-lg** [Icinga/puppet-icinga#92]
## Expected Behavior

Many modern modules for use with puppet 8 oder debian bookwork require the support of puppetlab-stdlib < 10.0.0.
Upgrading this module allows the usage in modern puppet setups.

## Current Behavior

The module requires puppetlabs-stdlib < 9.0.0
## Possible Solution

This feature request relates to #89 and #88 and will probably automaticly solved when upgrading the module.

**Comment by bk-lg** [comment]
@lbetz if you need some kind of support updating this module I can try to help with the puppet part if it doesn't envolves to much writing code other than puppet.

**Comment by lbetz** [comment]
Hi, and thx.

Comes with Puppet 8 support #89, working on branch enhancement/puppet8-support.

**Comment by lbetz** [comment]
refs #93
